--- # My First YAML Playbook for Ansiblek

- hosts: apacheweb  
  connection: ssh
  user: test
  sudo: yes
  gather_facts: no
  
  vars:
    playbook_version: 1.0
    vars_files:
      -/conf/copyrights.yml
      -/conf/webdefaults.yml  

  tasks: 
   - name: Installing apache webserver 
     yum: pkg=httpd state=latest
  
   - name: checking the lynx installation
     action: yum name=lynx state=present
