--- # The Wit For Moudule
- hosts: apacheweb
  sudo: yes
  gather_facts: no
  tasks: 
  - name: Installation Apache Tomcat
    action: yum name=tomcat state=installed
  - name: waiting for port 8080 to listen
    wait_for:
      port: 8080
      state: started
  - name: Verifying lynx installation
    action: yum name=lynx state=present
